import json

tr_det = {
  "01":{"desc":"Turk kargo firmalarini tek API altinda toplayan lojistik MVP. Tek istekte tum firmalardan sirali fiyat/sure doner. Musteri secer, sistem otomatik rezervasyon yapar.","hi":["Paralel firma sorgulari, normalize yanit semasi","Onay akisiyla otomatik rezervasyon pipeline","Tum firmalar arasi birlesik GPS takibi","Firma yonetimi ve gecmis admin paneli","Kurumsal coklu gonderi Excel aktarma"]},
  "02":{"desc":"OpenRouter yapay zeka destekli gelismis guvenlik acigi tarayicisi. 150+ istek/sn, %3.2 yanlis pozitif. WAF atlama ve adaptif gizlilikle 10+ zafiyet sinifinda kapsamli tespit.","hi":["833-payload WAF bypass mutasyon motoru","GPT-4 / Claude / Llama 3 yapay zeka triyaji","SQLi, XSS, CSRF, SSRF, LFI, XXE tespiti","CT log sayimiyla alt alan adi kesfi","%75+ test kapsami, 320+ senaryo"]},
  "03":{"desc":"Tibbi urun ve ticaret sirketleri icin tam CRM — musteri yonetimi, satis hatti, envanter, faturalandirma, finansal analitik ve is akisi otomasyonu. Gercek zamanli WebSocket bildirimler.","hi":["5 izin seviyesiyle rol tabanli erisim","Gercek zamanli KPI panosu ve satis hunisi","PDF/Excel ciktili otomatik faturalandirma","WebSocket canli bildirimler","Zamana dayali is akisi otomasyonu"]},
  "04":{"desc":"Gercek zamanli Firebase senkronizasyonu, Three.js 3D molekuler gorsellestirimler ve tam RTL destekli cok dilli sertifika yonetimi iceren kimyasal urun platformu.","hi":["Three.js WebGL ile 3D molekuler gorsellestirme","onSnapshot ile Firestore senkronizasyon","Cok dilli SDS/COA/MSDS sertifika yonetimi","CAS no, SKU, formul, marka aramalari","Guvenli rol tabanli admin paneli"]},
  "05":{"desc":"Cihazda JIMP goruntu isleme icin yerel Node.js koprusu olan iOS/Android depolama temizleyici. Yinelenen fotograflari tespit eder, IAP premium paketler, 17+ dil, Google Reklam, iOS widget.","hi":["GPU goruntu analizi icin yerel Node.js koprusu","Paylasilan App Group depolu iOS widget","6 sehir temali premium IAP paket","Google Mobile Ads odul ve gecis","Her yerde Lottie animasyonlari"]},
  "06":{"desc":"Cok borsali kripto icin dusuk gecikmeli otomatik HFT sistemi. Sistematik risk yonetimi, minimum kayma hedeflemesi ve gercek zamanli K/Z takibi ile yapilandirilabilir stop-loss.","hi":["Milisaniye alti WebSocket emir defteri alimi","Cok borsa birlesik emir soyutlamasi","Risk kontrolleriyle dinamik pozisyon boyutu","Gercek zamanli K/Z panosu ve dusus izleme","Geriye donuk test destekli strateji"]},
  "07":{"desc":"Freqtrade uzerinde uretim kaliteli otomatik alim satim botu. Ozel TA-Lib strateji mantigi, OHLCV geriye donuk test, canli alim satim ve performans panosu — Docker konteynerli.","hi":["TA-Lib gostergeli ozel strateji","Gecmis OHLCV verilerinde tam geriye donuk test","Docker konteynerli cok ortam dagitimi","Hyperopt parametre optimizasyonu","Canli islemler icin Telegram entegrasyonu"]},
  "08":{"desc":"TUBiTAK BiLGEM stajinda Agrobot projesi icin gelistirilen Ar-Ge drone veri izleme frontend. Arastirmacilar icin drone kaynakli saha verilerini otomatik olarak ceker ve gorsellestiriyor.","hi":["Gercek zamanli drone telemetri gorsellestirmesi","Otomatik backend API veri cekme","Resmi Ar-Ge ortaminda gelistirildi","Saha kullanimi icin React duyarli pano","TUBiTAK Agrobot pipeline entegrasyonu"]},
  "09":{"desc":"MKG Elektromekanik icin dijital donusum paketi. Tedarikci verilerinden otomatik faturalandirma ve Flutter personel takip uygulamasi — her ikisi uretimde aktif kullanim.","hi":["Kaziman katalogdan otomatik fatura","Sirket cihazlarinda Flutter personel uygulama","Supabase gercek zamanli PostgreSQL backend","Manuel is yukunu onemli olcude azaltti","ERP ve tedarikci akislariyla entegre"]},
  "10":{"desc":"Buyuk olcekte urun verisi cikaran otomatik AliExpress kazima pipeline. MKG otomatik faturalandirmasini guncel katalogla destekliyor.","hi":["Yuksek verimli AliExpress urun cikartma","Kategori siniflandirmali veri normallestirme","Dahili veritabanina sema esleme","Proxy rotasyonlu kazima","Dogrudan MKG faturalandirma beslemesi"]},
  "11":{"desc":"Next.js App Router ve Supabase ile gercek zamanli envanter takip uygulamasi. Canli stok izleme, urun yonetimi ve operasyonel ekipler icin anlik guncelleme.","hi":["Supabase canli aboneliklerle stok takibi","Kategori filtrelemeli urun katalogu","Next.js App Router sunucu bilesenli","Depo ekipleri icin rol tabanli erisim","Mobil duyarli depo kullanimi"]},
  "12":{"desc":"Aura kreatif studyo icin modern animasyon oncelikli ajans sitesi. Akici CSS animasyonlari, tamamen duyarli tasarim ve rafine marka kimligi. Aktif olarak canli ve bakim yapiliyor.","hi":["Akici scroll CSS animasyonlari","Mobilden ultra genis ekrana tam duyarli","Ozel tipografi ile marka kimligi","Optimize varliklarla hizli teslimat","Canli ve aktif bakim sureci"]},
  "13":{"desc":"Hasta randevu akisi, uzmanlik filtreli doktor arama, gercek zamanli musaitlik takibi ve klinik personel admin arayuzu iceren doktor randevu web uygulamasi.","hi":["Filtreli hasta doktor arama","Gercek zamanli randevu musaitlik takibi","Klinik personeli icin admin panosu","MongoDB randevu ve hasta veri modeli","JWT kimlik dogrulamali Express.js REST API"]},
  "14":{"desc":"GPU hizlandirmali WebGL canvas animasyonlariyla gorsek acidan iddiali 3D web deneyimi — yuksek voltajli elektrik ark efektleri, parcacik sistemleri ve 60fps dinamik aydinlatma.","hi":["Ozel shader GPU hizlandirmali WebGL","Yuksek voltajli elektrik ark efektleri","Dinamik aydinlatma ve bloom isleme","requestAnimationFrame ile 60fps","Sifir bagimlilikli WebGL pipeline"]}
}

de_det = {
  "01":{"desc":"Logistik-MVP das turkische Frachtanbieter unter einer API zusammenfasst. Eine Anfrage liefert sortierte Preise aller Anbieter. Kunde wahlt, System bucht automatisch, Echtzeit-Tracking vereint.","hi":["Parallele Anfragen, normiertes Antwortschema","Automatisiertes Buchungs-Pipeline","Einheitliches GPS-Tracking","Admin-Panel fur Anbieterverwaltung","Massen-Excel-Import fur Unternehmen"]},
  "02":{"desc":"Fortgeschrittener Sicherheitsscanner mit KI-Analyse uber OpenRouter. 150+ Req/Sek, 3,2% Falschpositivrate. WAF-Umgehung mit adaptiver Tarnung. Erkennung in 10+ Schwachstellenklassen.","hi":["833-Payload WAF-Bypass-Mutationsmotor","KI-Triage via GPT-4 / Claude / Llama 3","Erkennt SQLi, XSS, CSRF, SSRF, LFI, XXE","Subdomain-Entdeckung uber CT-Logs","75%+ Testabdeckung, 320+ Testfalle"]},
  "03":{"desc":"Vollstandiges CRM fur Medizinprodukt- und Handelsunternehmen. Kundenverwaltung, Vertriebspipeline, Lager, Rechnungsstellung, Finanzanalyse und Workflow-Automatisierung mit Glassmorphism-UI.","hi":["Rollenbasierter Zugang mit 5 Berechtigungsstufen","Echtzeit-KPI-Dashboard und Verkaufstrichter","Automatische Rechnungsstellung PDF/Excel","WebSocket-Live-Benachrichtigungen","Zeitbasierter Workflow-Automatisierungsmotor"]},
  "04":{"desc":"Chemisches Produktportal mit Echtzeit-Firebase-Sync, interaktiven 3D-Molekulvisualisierungen via Three.js und mehrsprachiger Zertifikatverwaltung (TR/EN/AR) mit RTL-Unterstutzung.","hi":["3D-Molekulvisualisierung mit Three.js WebGL","Echtzeit-Firestore-Sync mit onSnapshot","Mehrsprachige SDS/COA/MSDS-Verwaltung","Suche nach CAS-Nr., SKU, Formel, Marke","Sicheres rollenbasiertes Admin-Panel"]},
  "05":{"desc":"iOS/Android-Speicherbereiniger mit nativer Node.js-Bridge fur JIMP-Bildverarbeitung. Erkennt Duplikate, IAP-Premium-Pakete, 17+ Sprachen, Google Ads und iOS-Widget.","hi":["Native Node.js-Bridge fur GPU-Bildanalyse","iOS-Widget mit App-Group-Speicher","IAP mit 6 stadtethematischen Paketen","Google Mobile Ads Belohnung und Interstitial","Lottie-Animationen durchgehend"]},
  "06":{"desc":"Automatisiertes HFT-System mit niedriger Latenz fur Multi-Exchange-Krypto. WebSocket-Datenfeeds, systematisches Risikomanagement, minimale Slippage und konfigurierbares Stop-Loss.","hi":["Sub-Millisekunden WebSocket-Orderbuch","Einheitliche Multi-Exchange-Orderabstraktion","Dynamische Positionierung mit Risikokontrollen","Echtzeit P&L-Dashboard und Drawdown","Konfigurierbare Strategie mit Backtesting"]},
  "07":{"desc":"Automatisierter Trading-Bot auf Freqtrade in Produktionsqualitat. Benutzerdefinierte TA-Lib-Strategie, OHLCV-Backtesting, Live-Ausfuhrung und Leistungs-Dashboard Docker-containerisiert.","hi":["Benutzerdefinierte Strategie mit TA-Lib","Vollstandiges Backtesting auf historischen Daten","Docker Multi-Umgebungs-Deployment","Hyperopt-Parameteroptimierung","Telegram-Integration fur Live-Alarme"]},
  "08":{"desc":"F&E-Drohnen-Daten-Frontend beim TUBiTAK BiLGEM-Praktikum fur das Agrobot-Projekt. Ruft automatisch drohnenbasierte Felddaten ab und visualisiert sie fur Forscher und Feldbauingenieure.","hi":["Echtzeit-Drohnentelemetrie-Visualisierung","Automatischer Backend-API-Datenabruf","In formalem F&E-Umfeld entwickelt","React-responsives Feld-Dashboard","Integration in TUBiTAK Agrobot-Pipeline"]},
  "09":{"desc":"Digitales Transformationspaket fur MKG Elektromekanik. Automatische Rechnungsstellung aus Lieferantendaten und Flutter-Personalverfolgungsapp — beide aktiv in Tagesproduktion.","hi":["Automatische Rechnungsgenerierung aus Katalog","Flutter-Personalapp auf Unternehmensgeraten","Supabase Echtzeit-PostgreSQL-Backend","Manuelle Arbeitslast erheblich reduziert","Integration mit ERP und Lieferantendaten"]},
  "10":{"desc":"Automatisierte AliExpress-Scraping-Pipeline zur Extraktion und Normalisierung von Produktdaten im grossen Mastab. Beliefert MKG-Rechnungsstellung mit aktuellem Katalog.","hi":["Hochdurchsatz AliExpress-Extraktion","Datennormalisierung mit Kategorisierung","Schema-Mapping zur Produktdatenbank","Ratenbegrenzungsbewusstes Scraping","Direkteinspeisung in MKG-Pipeline"]},
  "11":{"desc":"Echtzeit-Bestandsverfolgungsapp mit Next.js App Router und Supabase. Live-Bestandsuberwachung, Produktverwaltung und Sofortaktualisierungen fur operative Teams.","hi":["Echtzeit-Bestand via Supabase-Abonnements","Produktkatalog mit Kategoriefilterung","Next.js App Router mit Server-Komponenten","Rollenbasierter Zugang fur Lagerteams","Mobile-responsive fur Lagereinsatz"]},
  "12":{"desc":"Moderner animationsbetonter Agentur-Webauftritt fur Aura Creative Studio. Flussige CSS-Animationen, vollstandig responsives Layout und verfeinerte Markenidentitat. Live und aktiv gepflegt.","hi":["Flussige scroll-getriebene CSS-Animationen","Vollstandig responsiv bis Ultra-Wide","Markenidentitat mit benutzerdefinierter Typografie","Schnelle statische Auslieferung","Live und aktiv in Produktion"]},
  "13":{"desc":"Arzttermin-Webapp mit patientenseitigem Buchungsablauf, Arztsuche mit Spezialisierungsfiltern, Echtzeit-Verfugbarkeitsverfolgung und Admin-Interface fur Klinikpersonal.","hi":["Patientenseitige Arztsuche mit Filtern","Echtzeit-Terminverfugbarkeit","Admin-Dashboard fur Klinikpersonal","MongoDB Termin- und Patientenmodell","JWT-Auth Express.js REST API"]},
  "14":{"desc":"Visuell ambitioniertes 3D-Weberlebnis mit GPU-beschleunigten WebGL-Canvas-Animationen — Hochspannungs-Lichtbogeneffekte, Partikelsysteme und dynamische Beleuchtung bei 60fps.","hi":["GPU-beschleunigtes WebGL mit Shadern","Hochspannungs-Lichtbogeneffekte","Dynamische Beleuchtung und Bloom","60fps mit requestAnimationFrame","Zero-Dependency WebGL-Pipeline"]}
}

for lang, det in [('tr', tr_det), ('de', de_det)]:
    path = f'/Users/berhudanbascan/Projects/porfolio/src/locales/{lang}.json'
    with open(path) as f:
        data = json.load(f)
    data['projects']['det'] = det
    with open(path, 'w') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"{lang} done")
